audio_stop_sound(BGM_Game2);
audio_play_sound(BGM_Menu, 0, true);
endtext[0] = "Obrigado por jogar!";
endtext[1] = "Feito por Felipe Alves Leao";
endtext[2] = "Creditos:";
endtext[3] = "Pixel art: Pixel Adventure por Pixel Frog";
endtext[4] = "Mythical Dungeon Tileset por Tilation";
endtext[5] = "Efeitos sonoros:";
endtext[6] = "Sons do menu feito por philRacoIndie";
endtext[7] = "Som de morte feito por HappyParakeet";
endtext[8] = "Musica: ";
endtext[9] = "8-bit Menu por FeslyianStudios";
endtext[10] = "Grassland Theme por CodeManu";
endtext[11] = "8bit Dungeon Level por Kevin MacLeod";
endtext[12] = "Fim!";
spd = 0.5;
letters = 0;
currentline = 0;
length = string_length(endtext[currentline]);
text="";
